### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'ndcg' 

### ISSUE THREAD

**Issue by tigerneil** [tohtsky/irspack#67]
Thank you for building this great project. 

I found a AttributeError: 'DataFrame' object has no attribute 'ndcg'. Could you give some hint for this. Maybe the version caused such an issue. 

```
[I 2021-04-15 22:32:57,587] Trial 19 finished with value: -0.1701716280
513936 and parameters: {'top_k': 15, 'normalize_weight': True}. Best is trial 13
 with value: -0.38695462976440437.
>>>
>>> # maximal ndcg around 0.38 ~ 0.39
>>> trial_dfs.ndcg.max()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    trial_dfs.ndcg.max()
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line
 5460, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ndcg'
```

**Comment by tigerneil** [comment]
`trial_dfs['ndcg@10'].max()` works.

**Comment by tohtsky** [comment]
Hello and thank you for reporting the issue!

>Maybe the version caused such an issue.

Exactly. I have recently (in version 0.1.11) changed the validation data frames column name to explicitly show the cutoff.
I'll be upgrading the Readme ASAP.
